print('test 1')
raise Exception('some test error')
